### PR TITLE
postag problem with underscore

### PR DESCRIPTION
**Pull request by Masoumeh**
postag problem with underscore is solved.

### CODE REVIEW

**Comment by balmas** [comment]
@Masoumeh on the surface this seems okay, but a test is failing:

https://travis-ci.org/latin-language-toolkit/arethusa/builds/66000308

PhantomJS 1.9.8 (Linux 0.0.0) morph this.concatenatedAttributes returns a concatenated string of all attributes (short representation), joined by a dot FAILED

	Expected 'noun.---' to equal 'noun'.

This is a little surprising to me because if anything I would have expected the failed test to be looking for an _ instead of a -, and the error indicates an extra --- is coming where nothing was expected.  Can you investigate this a little? Thanks!

**Comment by Masoumeh** [comment]
Hi @balmas 
I think "---" comes from the arethusaMock token "01" at which the the postag is set to "n-". I think that's why it's expecting "n.---". Could you please check it once more with the new changes I've already pushed?
It works when I try it.

**Comment by balmas** [comment]
Ah, okay I understand what is happening here. I was afraid there was a specific reason we had used an "_" here instead of "-" and I see what it is now. The problem is the overloading of the meaning of "-". In the postag, it's perfectly legitimate to have a "-" in one of the positions, and it doesn't usually mean that the data wasn't supplied, it could mean that it's not applicable for the specific form.

So, take a look at the attached screenshot . The first form, citer1, has 
adj.---.sg.---.----.---.---

Filling in the "---" for the short name of the attribute (e.g. from the `short` property on the `emptyAttribute` object).  The actual postag value here is `a-s---fbc`  and the positions in value that are specified with `-` aren't applicable for this form (you can ask @gcelano to explain the postag to you further).

(I suspect this is also the reason for the "n-" in the test case, to test exactly this problem - we should add a comment to that effect!)

So, we need a way to distinguish between when it's empty (i.e. '-') because the user didn't know when creating a new form, and when it's empty because it's not applicable.  The original solution was to use "_" .

@gcelano -- it's not actually such an easy problem to solve, if we do want to be able to distinguish this "i don't know" case for an individual component of the postag.  What are your thoughts?

screenshot from 2015-06-11 10 17 32

**Comment by gcelano** [comment]
If the problem is to find a way to distinguish between cases where there is
no value applicable and the "I do not know" option, a solution could just
be to mark the latter with a letter such as "k". I should add that in the
morphological annotation the option "I do not know",
which is represented as "---" in Arethusa, applies almost exclusively to
the cases where someone introduces an elliptical node and cannot specify,
for example, some morphological features of the word. At the beginning,
this was simply not possible, because the system forced anyone to choose a
value for
each field (i.e., for a verb I should always specify mood, tense, etc...).

That said, the only problem that I see in distinguishing is that an
incompatibility with the Morpheus output might arise: e.g., for adjectives
the last field is grade (positive, comparative, superlative, ---). Many
annotators select "---" instead of "positive" because in Morpheus this last
value is very often "-" (the meaning of "positive" is not very clear in
Morpheus, so what one would like to have is simply "-" in the XML).
In this case selecting "---" is not really "I do not know" . I knew of this
problem when comparing annotations. Do we really need to distinguish?
Cannot we simply always use "-", meaning that for one reason or another
that value is not available?

2015-06-11 16:33 GMT+02:00 Bridget Almas <notifications@github.com>:

> Ah, okay I understand what is happening here. I was afraid there was a
> specific reason we had used an "_" here instead of "-" and I see what it is
> now. The problem is the overloading of the meaning of "-". In the postag,
> it's perfectly legitimate to have a "-" in one of the positions, and it
> doesn't usually mean that the data wasn't supplied, it could mean that it's
> not applicable for the specific form.
>
> So, take a look at the attached screenshot . The first form, citer1, has
> adj.---.sg.---.----.---.---
>
> Filling in the "---" for the short name of the attribute (e.g. from the
> short property on the emptyAttribute object). The actual postag value
> here is a-s---fbc and the positions in value that are specified with -
> aren't applicable for this form (you can ask @gcelano
> <https://github.com/gcelano> to explain the postag to you further).
>
> (I suspect this is also the reason for the "n-" in the test case, to test
> exactly this problem - we should add a comment to that effect!)
>
> So, we need a way to distinguish between when it's empty (i.e. '-')
> because the user didn't know when creating a new form, and when it's empty
> because it's not applicable. The original solution was to use "_" .
>
> @gcelano <https://github.com/gcelano> -- it's not actually such an easy
> problem to solve, if we do want to be able to distinguish this "i don't
> know" case for an individual component of the postag. What are your
> thoughts?
>
> [image: screenshot from 2015-06-11 10 17 32]
> <https://cloud.githubusercontent.com/assets/644870/8109199/7fab6118-1023-11e5-9b1d-bfa2d8260531.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/latin-language-toolkit/arethusa/pull/694#issuecomment-111155938>
> .
>



-- 
Dr. Giuseppe G. A. Celano
Postdoctoral Researcher
Universität Leipzig
Institute of Computer Science,
​Section of ​
Digital
​ ​
Humanities
​

Augustusplatz 10
04109 Leipzig
​ (DE)​

E-mail: giuseppegacelano@gmail.com
            giuseppe.celano@tufts.edu
            celano@informatik.uni-leipzig.de
Web site 1: http://www.dh.uni-leipzig.de/wo/team/
Web site 2: https://sites.google.com/site/giuseppegacelano/

**Comment by balmas** [comment]
@gcelano I think we could probably use "-" for both cases if there isn't a strong need to be able to distinguish this in the data.

@Masoumeh to do this, then we need to change the way the code handles the display of the short/long information for the empty attribute when supplying a new morph form, because the way it's overloaded right now doesn't allow us to distinguish between when we want to display "---" in the abbreviated version of the morphology (such as when you are inputting a new form) vs nothing (such as the case when you are showing the concatonated abbreviated forms for an existing postag value.

**Comment by balmas** [comment]
NB I would like @vgorman1 and Bob Gorman to chime in on this before we make the change though.

**Comment by rgorman** [comment]
Hey, all:

If I understand the question correctly, the gist of the matter is that Morpheus uses "-" for morphological categories in the meaning "does not apply" and "unknown." On the other hand, Arethusa codes unknown with "_", when so chosen by the annotator. But there are other permutations as @gcelano   points out.

**Comment by Masoumeh** [comment]
As I have understood correctly, there is not a real usage to have different signs for both "does not apply" and "unknown" reflected in the postag. So @balmas whY don't we simply omit the underscore and go with "-" for both cases?

**Comment by balmas** [comment]
@Masoumeh that does seem to be the consensus.  If nobody is depending upon the use "_" to reflect unknown, which sounds to be the case from @rgorman and @gcelano then I think we take it out.

But, there is still another code change to be made here then, because we don't want the "---" to be appearing in place of the - where the short code is displayed in the concatonated abbreviations, so we do need to change the way this information is shown in the dropdowns for the new forms. Let me know if this isn't clear. Thanks!

**Comment by Masoumeh** [comment]
I changed the concatenated abbreviation regarding my understanding! Now, it just omits the --- in the long form. Is it what you mean??

**Comment by balmas** [comment]
@Masoumeh well, it's not exactly what I meant, but it's probably just as good.  Thanks!

**Pull request merged**
